//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Slizlba.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class IzlozbaSlika
    {
        public int Id { get; set; }
        public int SlikaID { get; set; }
        public int IzlozbaID { get; set; }
    
        public virtual Izlozba Izlozba { get; set; }
        public virtual Slika Slika { get; set; }
    }
}
