//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Slizlba.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesto
    {
        public Mesto()
        {
            this.Izlozbas = new HashSet<Izlozba>();
        }
    
        public int Id { get; set; }
        public string Naziv { get; set; }
    
        public virtual ICollection<Izlozba> Izlozbas { get; set; }
    }
}
