//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Slizlba.DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SlilzozbeEntities : DbContext
    {
        public SlilzozbeEntities()
            : base("name=SlilzozbeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Autor> Autors { get; set; }
        public DbSet<Izlozba> Izlozbas { get; set; }
        public DbSet<IzlozbaSlika> IzlozbaSlikas { get; set; }
        public DbSet<Mesto> Mestoes { get; set; }
        public DbSet<Slika> Slikas { get; set; }
        public DbSet<SlikaAutor> SlikaAutors { get; set; }
        public DbSet<SlikaTehnika> SlikaTehnikas { get; set; }
        public DbSet<Tehnika> Tehnikas { get; set; }
    }
}
