//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Slizlba.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlikaAutor
    {
        public int idSlikaAutor { get; set; }
        public int idSlika { get; set; }
        public int idAutor { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual Slika Slika { get; set; }
    }
}
