//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Slizlba.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlikaTehnika
    {
        public int idSlikaTehnika { get; set; }
        public int idSlika { get; set; }
        public int idTehnika { get; set; }
    
        public virtual Slika Slika { get; set; }
        public virtual Tehnika Tehnika { get; set; }
    }
}
