//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Slizlba.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tehnika
    {
        public Tehnika()
        {
            this.SlikaTehnikas = new HashSet<SlikaTehnika>();
        }
    
        public int Id { get; set; }
        public string Naziv { get; set; }
    
        public virtual ICollection<SlikaTehnika> SlikaTehnikas { get; set; }
    }
}
